---
kind: Service
apiVersion: v1
metadata:
    name: "{{ .Values.SERVICE_NAME }}"
    annotations:
        qubership.cloud/start.stage: '0'
spec:
    ports:
        - name: web
          port: 8080
          targetPort: 8080
    selector:
        name: "{{ .Values.SERVICE_NAME }}"