# ============== DEPLOYMENT VARIABLES ============================
SERVICE_NAME: maas-service
APPLICATION_NAME: maas
NAMESPACE: maas

READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname

MAAS_ACCOUNT_MANAGER_USERNAME: manager

MAAS_DEPLOYER_CLIENT_USERNAME: client

MEMORY_LIMIT: "100Mi"
CPU_REQUEST: "400m"
CPU_LIMIT: "2000m"
REPLICAS: 1

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: info
DB_POOL_SIZE: 5

EXECUTION_MODE: active
DB_POSTGRESQL_TLS_SKIPVERIFY: false
KAFKA_CLIENT_TIMEOUT: "10s"

